export const ADD_EXPENSE_SUCCESS = 'ADD_EXPENSE_SUCCESS';
export const DELETE_EXPENSE_SUCCESS = 'DELETE_EXPENSE_SUCCESS';
export const GET_EXPENSES_SUCCESS = 'GET_EXPENSES_SUCCESS';
export const GET_EXPENSES_ERROR = 'GET_EXPENSES_ERROR';
